In [ ]:
# !pip install folium

Requirement already satisfied: folium in c:\users\admin\miniconda3\envs\streamlit_env\lib\site-packages (0.20.0)
Requirement already satisfied: branca>=0.6.0 in c:\users\admin\miniconda3\envs\streamlit_env\lib\site-packages (from folium) (0.8.1)
Requirement already satisfied: jinja2>=2.9 in c:\users\admin\miniconda3\envs\streamlit_env\lib\site-packages (from folium) (3.1.6)
Requirement already satisfied: numpy in c:\users\admin\miniconda3\envs\streamlit_env\lib\site-packages (from folium) (2.0.2)
Requirement already satisfied: requests in c:\users\admin\miniconda3\envs\streamlit_env\lib\site-packages (from folium) (2.32.4)
Requirement already satisfied: xyzservices in c:\users\admin\miniconda3\envs\streamlit_env\lib\site-packages (from folium) (2025.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\admin\miniconda3\envs\streamlit_env\lib\site-packages (from jinja2>=2.9->folium) (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\admin\miniconda3\envs\streamlit_env\lib\site-packages (from requests->folium) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\miniconda3\envs\streamlit_env\lib\site-packages (from requests->folium) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\admin\miniconda3\envs\streamlit_env\lib\site-packages (from requests->folium) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\miniconda3\envs\streamlit_env\lib\site-packages (from requests->folium) (2025.8.3)

In [4]:
import folium

In [5]:
loc = [37.5662952, 126.9779451]

In [6]:
map = folium.Map(location=loc, zoomstart=16)
folium.Marker(location=loc).add_to(map)
map

In [7]:
import requests
from pandas import json_normalize

In [8]:
targetSite='https://www.starbucks.co.kr/store/getStore.do?r=8K3XF06R9Q'
req=requests.post(targetSite, data={
'ins_lat': 37.563398,
'ins_lng': 126.9863309,
'p_sido_cd': '01',
'p_gugun_cd': '',
'in_biz_cd': '',
'iend': 600,
'set_date': ''
})
starbucks=req.json()
print(type(starbucks))

<class 'dict'>

In [9]:
starbucks

{'list': [{'seq': 0,
   'sido_cd': None,
   'sido_nm': None,
   'gugun_cd': None,
   'gugun_nm': None,
   'code_order': None,
   'view_yn': None,
   'store_num': None,
   'sido': None,
   'gugun': None,
   'address': None,
   'new_img_nm': None,
   'p_pro_seq': 0,
   'p_view_yn': None,
   'p_sido_cd': '',
   'p_gugun_cd': '',
   'p_store_nm': None,
   'p_theme_cd': None,
   'p_wireless_yn': None,
   'p_smoking_yn': None,
   'p_book_yn': None,
   'p_music_yn': None,
   'p_terrace_yn': None,
   'p_table_yn': None,
   'p_takeout_yn': None,
   'p_parking_yn': None,
   'p_dollar_assent': None,
   'p_card_recharge': None,
   'p_subway_yn': None,
   'stb_store_file_renew': None,
   'stb_store_theme_renew': None,
   'stb_store_time_renew': None,
   'stb_store_lsm': None,
   's_code': '1509',
   's_name': '역삼아레나빌딩',
   'tel': '1522-3232',
   'dlvry_call_cntr_phno': None,
   'fax': '02-568-3763',
   'sido_code': '01',
   'sido_name': '서울',
   'gugun_code': '0101',
   'gugun_name': '강남구',
   'addr': '서울특별시 강남구 역삼동 721-13 아레나빌딩',
   'park_info': None,
   'new_state': None,
   'theme_state': 'Z9999@T05@T08@T16@T17@T20@T21@T30@T32@T36@@T43@T52@T56@T57@T64@T65@T69@T71@P80@P90',
   'new_bool': 0,
   'search_text': '',
   'ins_lat': '',
   'ins_lng': '',
   'in_distance': 0,
   'out_distance': '8.55',
   'all_search_cnt': -1,
   'addr_search_cnt': -1,
   'store_search_cnt': -1,
   'rowCount': 30,
   'store_nm': '',
   'store_cd': 0,
   's_biz_code': '3762',
   'new_icon': 'N',
   'set_user': '',
   'favorites': 0,
   'map_desc': None,
   'notice': None,
   'defaultimage': '/upload/store/2019/06/[3762]_20190612101444_j4839.JPG',
   'etcimage': None,
   'in_biz_cd': None,
   'in_store_cd': None,
   'in_favorites': None,
   'in_user_id': None,
   'in_biz_cds': 0,
   'in_biz_arr': None,
   'in_biz_arrdata': None,
   'in_scodes': 0,
   'in_scode_arr': None,
   'in_scode_arrdata': None,
   'disp': None,
   'set_date': None,
   'hlytag': None,
   'hlytag_msg': None,
   'vSal': '',
   'istart': 1,
   'iend': 60,
   'open_dt': '20190613',
   'gold_card': 0,
   'ip_lat': '',
   'ip_long': '',
   'espresso': '',
   'new_store': '',
   'premiere_food': '',
   'doro_address': '서울특별시 강남구 언주로 425 (역삼동)',
   'cold_blew': '',
   'my_siren_order_store_yn': 'N',
   'whcroad_yn': 'WHCROAD',
   'skuNo': '',
   'skuName': '',
   'skuImgUrl': '',
   'stock_count': 0,
   'store_area_name': None,
   'store_area_code': 'A01',
   'is_open': None,
   'ev_open_yn': None,
   'option': None,
   'gift_stock_yn': None,
   'lat': '37.501087',
   'lot': '127.043069',
   't20': 0,
   't04': 0,
   't03': 0,
   't01': 0,
   't12': 0,
   't09': 0,
   't06': 0,
   't10': 0,
   'p10': 0,
   'p50': 0,
   'p20': 0,
   'p60': 0,
   'p30': 0,
   'p70': 0,
   'p40': 0,
   'p80': 0,
   't22': 0,
   't21': 0,
   'p90': 0,
   'p01': 0,
   't05': 0,
   't30': 0,
   't36': 0,
   't27': 0,
   't29': 0,
   't43': 0,
   't48': 0,
   'z9999': 0,
   't64': 0,
   't66': 0,
   'p02': 0},
  {'seq': 0,
   'sido_cd': None,
   'sido_nm': None,
   'gugun_cd': None,
   'gugun_nm': None,
   'code_order': None,
   'view_yn': None,
   'store_num': None,
   'sido': None,
   'gugun': None,
   'address': None,
   'new_img_nm': None,
   'p_pro_seq': 0,
   'p_view_yn': None,
   'p_sido_cd': '',
   'p_gugun_cd': '',
   'p_store_nm': None,
   'p_theme_cd': None,
   'p_wireless_yn': None,
   'p_smoking_yn': None,
   'p_book_yn': None,
   'p_music_yn': None,
   'p_terrace_yn': None,
   'p_table_yn': None,
   'p_takeout_yn': None,
   'p_parking_yn': None,
   'p_dollar_assent': None,
   'p_card_recharge': None,
   'p_subway_yn': None,
   'stb_store_file_renew': None,
   'stb_store_theme_renew': None,
   'stb_store_time_renew': None,
   'stb_store_lsm': None,
   's_code': '1434',
   's_name': '논현역사거리',
   'tel': '1522-3232',
   'dlvry_call_cntr_phno': None,
   'fax': '02-3442-3673',
   'sido_code': '01',
   'sido_name': '서울',
   'gugun_code': '0101',
   'gugun_name': '강남구',
   'addr': '서울특별시 강남구 논현동 142-2 정일빌딩',
   'park_info': None,
   'new_state': None,
   'theme_state': 'Z9999@T05@T08@T16@T17@T20@T21@T22@T30@T32@T36@@T52@T56@T57@T64@T69@P70@P80@P90',
   'new_bool': 0,
   'search_text': '',
   'ins_lat': '',
   'ins_lng': '',
   'in_distance': 0,
   'out_distance': '6.71',
   'all_search_cnt': -1,
   'addr_search_cnt': -1,
   'store_search_cnt': -1,
   'rowCount': 30,
   'store_nm': '',
   'store_cd': 0,
   's_biz_code': '3672',
   'new_icon': 'N',
   'set_user': '',
   'favorites': 0,
   'map_desc': None,
   'notice': None,
   'defaultimage': '/upload/store/2025/07/3672_20250709034455_lnuoo.jpg',
   'etcimage': None,
   'in_biz_cd': None,
   'in_store_cd': None,
   'in_favorites': None,
   'in_user_id': None,
   'in_biz_cds': 0,
   'in_biz_arr': None,
   'in_biz_arrdata': None,
   'in_scodes': 0,
   'in_scode_arr': None,
   'in_scode_arrdata': None,
   'disp': None,
   'set_date': None,
   'hlytag': None,
   'hlytag_msg': None,
   'vSal': '',
   'istart': 1,
   'iend': 60,
   'open_dt': '20181123',
   'gold_card': 0,
   'ip_lat': '',
   'ip_long': '',
   'espresso': '',
   'new_store': '',
   'premiere_food': '',
   'doro_address': '서울특별시 강남구 강남대로 538 (논현동)',
   'cold_blew': '',
   'my_siren_order_store_yn': 'N',
   'whcroad_yn': '',
   'skuNo': '',
   'skuName': '',
   'skuImgUrl': '',
   'stock_count': 0,
   'store_area_name': None,
   'store_area_code': 'A01',
   'is_open': None,
   'ev_open_yn': None,
   'option': None,
   'gift_stock_yn': None,
   'lat': '37.510178',
   'lot': '127.022223',
   't20': 0,
   't04': 0,
   't03': 0,
   't01': 0,
   't12': 0,
   't09': 0,
   't06': 0,
   't10': 0,
   'p10': 0,
   'p50': 0,
   'p20': 0,
   'p60': 0,
   'p30': 0,
   'p70': 0,
   'p40': 0,
   'p80': 0,
   't22': 0,
   't21': 0,
   'p90': 0,
   'p01': 0,
   't05': 0,
   't30': 0,
   't36': 0,
   't27': 0,
   't29': 0,
   't43': 0,
   't48': 0,
   'z9999': 0,
   't64': 0,
   't66': 0,
   'p02': 0},
  {'seq': 0,
   'sido_cd': None,
   'sido_nm': None,
   'gugun_cd': None,
   'gugun_nm': None,
   'code_order': None,
   'view_yn': None,
   'store_num': None,
   'sido': None,
   'gugun': None,
   'address': None,
   'new_img_nm': None,
   'p_pro_seq': 0,
   'p_view_yn': None,
   'p_sido_cd': '',
   'p_gugun_cd': '',
   'p_store_nm': None,
   'p_theme_cd': None,
   'p_wireless_yn': None,
   'p_smoking_yn': None,
   'p_book_yn': None,
   'p_music_yn': None,
   'p_terrace_yn': None,
   'p_table_yn': None,
   'p_takeout_yn': None,
   'p_parking_yn': None,
   'p_dollar_assent': None,
   'p_card_recharge': None,
   'p_subway_yn': None,
   'stb_store_file_renew': None,
   'stb_store_theme_renew': None,
   'stb_store_time_renew': None,
   'stb_store_lsm': None,
   's_code': '1595',
   's_name': '신사역성일빌딩',
   'tel': '1522-3232',
   'dlvry_call_cntr_phno': None,
   'fax': '02-547-3859',
   'sido_code': '01',
   'sido_name': '서울',
   'gugun_code': '0101',
   'gugun_name': '강남구',
   'addr': '서울특별시 강남구 논현동 18-4 성일빌딩',
   'park_info': None,
   'new_state': None,
   'theme_state': 'T05@T08@T16@T17@T20@T21@T30@T32@T34@@@@T52@T56@T57@T64@T68@T69@P80@P90',
   'new_bool': 0,
   'search_text': '',
   'ins_lat': '',
   'ins_lng': '',
   'in_distance': 0,
   'out_distance': '6.28',
   'all_search_cnt': -1,
   'addr_search_cnt': -1,
   'store_search_cnt': -1,
   'rowCount': 30,
   'store_nm': '',
   'store_cd': 0,
   's_biz_code': '3858',
   'new_icon': 'N',
   'set_user': '',
   'favorites': 0,
   'map_desc': None,
   'notice': None,
   'defaultimage': '/upload/store/2022/01/[3858]_20220127064243_5khni.jpg',
   'etcimage': None,
   'in_biz_cd': None,
   'in_store_cd': None,
   'in_favorites': None,
   'in_user_id': None,
   'in_biz_cds': 0,
   'in_biz_arr': None,
   'in_biz_arrdata': None,
   'in_scodes': 0,
   'in_scode_arr': None,
   'in_scode_arrdata': None,
   'disp': None,
   'set_date': None,
   'hlytag': None,
   'hlytag_msg': None,
   'vSal': '',
   'istart': 1,
   'iend': 60,
   'open_dt': '20191219',
   'gold_card': 0,
   'ip_lat': '',
   'ip_long': '',
   'espresso': '',
   'new_store': '',
   'premiere_food': '',
   'doro_address': '서울특별시 강남구 강남대로 584 (논현동)',
   'cold_blew': '',
   'my_siren_order_store_yn': 'N',
   'whcroad_yn': '',
   'skuNo': '',
   'skuName': '',
   'skuImgUrl': '',
   'stock_count': 0,
   'store_area_name': None,
   'store_area_code': 'A01',
   'is_open': None,
   'ev_open_yn': None,
   'option': None,
   'gift_stock_yn': None,
   'lat': '37.5139309',
   'lot': '127.0206057',
   't20': 0,
   't04': 0,
   't03': 0,
   't01': 0,
   't12': 0,
   't09': 0,
   't06': 0,
   't10': 0,
   'p10': 0,
   'p50': 0,
   'p20': 0,
   'p60': 0,
   'p30': 0,
   'p70': 0,
   'p40': 0,
   'p80': 0,
   't22': 0,
   't21': 0,
   'p90': 0,
   'p01': 0,
   't05': 0,
   't30': 0,
   't36': 0,
   't27': 0,
   't29': 0,
   't43': 0,
   't48': 0,
   'z9999': 0,
   't64': 0,
   't66': 0,
   'p02': 0},
  {'seq': 0,
   'sido_cd': None,
   'sido_nm': None,
   'gugun_cd': None,
   'gugun_nm': None,
   'code_order': None,
   'view_yn': None,
   'store_num': None,
   'sido': None,
   'gugun': None,
   'address': None,
   'new_img_nm': None,
   'p_pro_seq': 0,
   'p_view_yn': None,
   'p_sido_cd': '',
   'p_gugun_cd': '',
   'p_store_nm': None,
   'p_theme_cd': None,
   'p_wireless_yn': None,
   'p_smoking_yn': None,
   'p_book_yn': None,
   'p_music_yn': None,
   'p_terrace_yn': None,
   'p_table_yn': None,
   'p_takeout_yn': None,
   'p_parking_yn': None,
   'p_dollar_assent': None,
   'p_card_recharge': None,
   'p_subway_yn': None,
   'stb_store_file_renew': None,
   'stb_store_theme_renew': None,
   'stb_store_time_renew': None,
   'stb_store_lsm': None,
   's_code': '1527',
   's_name': '국기원사거리',
   'tel': '1522-3232',
   'dlvry_call_cntr_phno': None,
   'fax': '02-568-3669',
   'sido_code': '01',
   'sido_name': '서울',
   'gugun_code': '0101',
   'gugun_name': '강남구',
   'addr': '서울특별시 강남구 역삼동 648-22 동찬빌딩',
   'park_info': None,
   'new_state': None,
   'theme_state': 'Z9999@T05@T08@T16@T17@T20@T21@T30@T32@T34@@T36@T52@T56@T57@T64@T69@P70@P90',
   'new_bool': 0,
   'search_text': '',
   'ins_lat': '',
   'ins_lng': '',
   'in_distance': 0,
   'out_distance': '8.14',
   'all_search_cnt': -1,
   'addr_search_cnt': -1,
   'store_search_cnt': -1,
   'rowCount': 30,
   'store_nm': '',
   'store_cd': 0,
   's_biz_code': '3669',
   'new_icon': 'N',
   'set_user': '',
   'favorites': 0,
   'map_desc': None,
   'notice': None,
   'defaultimage': '/upload/store/2019/07/[3669]_20190730073527_5nk40.jpg',
   'etcimage': None,
   'in_biz_cd': None,
   'in_store_cd': None,
   'in_favorites': None,
   'in_user_id': None,
   'in_biz_cds': 0,
   'in_biz_arr': None,
   'in_biz_arrdata': None,
   'in_scodes': 0,
   'in_scode_arr': None,
   'in_scode_arrdata': None,
   'disp': None,
   'set_date': None,
   'hlytag': None,
   'hlytag_msg': None,
   'vSal': '',
   'istart': 1,
   'iend': 60,
   'open_dt': '20190731',
   'gold_card': 0,
   'ip_lat': '',
   'ip_long': '',
   'espresso': '',
   'new_store': '',
   'premiere_food': '',
   'doro_address': '서울특별시 강남구 테헤란로 125 (역삼동)',
   'cold_blew': '',
   'my_siren_order_store_yn': 'N',
   'whcroad_yn': 'WHCROAD',
   'skuNo': '',
   'skuName': '',
   'skuImgUrl': '',
   'stock_count': 0,
   'store_area_name': None,
   'store_area_code': 'A01',
   'is_open': None,
   'ev_open_yn': None,
   'option': None,
   'gift_stock_yn': None,
   'lat': '37.499517',
   'lot': '127.031495',
   't20': 0,
   't04': 0,
   't03': 0,
   't01': 0,
   't12': 0,
   't09': 0,
   't06': 0,
   't10': 0,
   'p10': 0,
   'p50': 0,
   'p20': 0,
   'p60': 0,
   'p30': 0,
   'p70': 0,
   'p40': 0,
   'p80': 0,
   't22': 0,
   't21': 0,
   'p90': 0,
   'p01': 0,
   't05': 0,
   't30': 0,
   't36': 0,
   't27': 0,
   't29': 0,
   't43': 0,
   't48': 0,
   'z9999': 0,
   't64': 0,
   't66': 0,
   'p02': 0},
  {'seq': 0,
   'sido_cd': None,
   'sido_nm': None,
   'gugun_cd': None,
   'gugun_nm': None,
   'code_order': None,
   'view_yn': None,
   'store_num': None,
   'sido': None,
   'gugun': None,
   'address': None,
   'new_img_nm': None,
   'p_pro_seq': 0,
   'p_view_yn': None,
   'p_sido_cd': '',
   'p_gugun_cd': '',
   'p_store_nm': None,
   'p_theme_cd': None,
   'p_wireless_yn': None,
   'p_smoking_yn': None,
   'p_book_yn': None,
   'p_music_yn': None,
   'p_terrace_yn': None,
   'p_table_yn': None,
   'p_takeout_yn': None,
   'p_parking_yn': None,
   'p_dollar_assent': None,
   'p_card_recharge': None,
   'p_subway_yn': None,
   'stb_store_file_renew': None,
   'stb_store_theme_renew': None,
   'stb_store_time_renew': None,
   'stb_store_lsm': None,
   's_code': '1468',
   's_name': '대치재경빌딩',
   'tel': '1522-3232',
   'dlvry_call_cntr_phno': None,
   'fax': '02-568-3705',
   'sido_code': '01',
   'sido_name': '서울',
   'gugun_code': '0101',
   'gugun_name': '강남구',
   'addr': '서울특별시 강남구 대치동 599 대원빌딩',
   'park_info': None,
   'new_state': None,
   'theme_state': 'Z9999@@T05@T08@T16@T17@T20@T21@T22@@@T30@T32@T36@@T43@T52@T56@T57@T64@T65@T69@T71@P90',
   'new_bool': 0,
   'search_text': '',
   'ins_lat': '',
   'ins_lng': '',
   'in_distance': 0,
   'out_distance': '10.18',
   'all_search_cnt': -1,
   'addr_search_cnt': -1,
   'store_search_cnt': -1,
   'rowCount': 30,
   'store_nm': '',
   'store_cd': 0,
   's_biz_code': '3703',
   'new_icon': 'N',
   'set_user': '',
   'favorites': 0,
   'map_desc': None,
   'notice': None,
   'defaultimage': '/upload/store/2023/12/[3703]_20231217121347_eqnky.jpg',
   'etcimage': None,
   'in_biz_cd': None,
   'in_store_cd': None,
   'in_favorites': None,
   'in_user_id': None,
   'in_biz_cds': 0,
   'in_biz_arr': None,
   'in_biz_arrdata': None,
   'in_scodes': 0,
   'in_scode_arr': None,
   'in_scode_arrdata': None,
   'disp': None,
   'set_date': None,
   'hlytag': None,
   'hlytag_msg': None,
   'vSal': '',
   'istart': 1,
   'iend': 60,
   'open_dt': '20190214',
   'gold_card': 0,
   'ip_lat': '',
   'ip_long': '',
   'espresso': '',
   'new_store': '',
   'premiere_food': '',
   'doro_address': '서울특별시 강남구 남부순환로 2947 (대치동)',
   'cold_blew': '',
   'my_siren_order_store_yn': 'N',
   'whcroad_yn': 'WHCROAD',
   'skuNo': '',
   'skuName': '',
   'skuImgUrl': '',
   'stock_count': 0,
   'store_area_name': None,
   'store_area_code': 'A01',
   'is_open': None,
   'ev_open_yn': None,
   'option': None,
   'gift_stock_yn': None,
   'lat': '37.494668',
   'lot': '127.062583',
   't20': 0,
   't04': 0,
   't03': 0,
   't01': 0,
   't12': 0,
   't09': 0,
   't06': 0,
   't10': 0,
   'p10': 0,
   'p50': 0,
   'p20': 0,
   'p60': 0,
   'p30': 0,
   'p70': 0,
   'p40': 0,
   'p80': 0,
   't22': 0,
   't21': 0,
   'p90': 0,
   'p01': 0,
   't05': 0,
   't30': 0,
   't36': 0,
   't27': 0,
   't29': 0,
   't43': 0,
   't48': 0,
   'z9999': 0,
   't64': 0,
   't66': 0,
   'p02': 0},
  {'seq': 0,
   'sido_cd': None,
   'sido_nm': None,
   'gugun_cd': None,
   'gugun_nm': None,
   'code_order': None,
   'view_yn': None,
   'store_num': None,
   'sido': None,
   'gugun': None,
   'address': None,
   'new_img_nm': None,
   'p_pro_seq': 0,
   'p_view_yn': None,
   'p_sido_cd': '',
   'p_gugun_cd': '',
   'p_store_nm': None,
   'p_theme_cd': None,
   'p_wireless_yn': None,
   'p_smoking_yn': None,
   'p_book_yn': None,
   'p_music_yn': None,
   'p_terrace_yn': None,
   'p_table_yn': None,
   'p_takeout_yn': None,
   'p_parking_yn': None,
   'p_dollar_assent': None,
   'p_card_recharge': None,
   'p_subway_yn': None,
   'stb_store_file_renew': None,
   'stb_store_theme_renew': None,
   'stb_store_time_renew': None,
   'stb_store_lsm': None,
   's_code': '1640',
   's_name': '봉은사역',
   'tel': '1522-3232',
   'dlvry_call_cntr_phno': None,
   'fax': '02-517-3913',
   'sido_code': '01',
   'sido_name': '서울',
   'gugun_code': '0101',
   'gugun_name': '강남구',
   'addr': '서울특별시 강남구 삼성동 108-6 JBK TOWER 빌딩',
   'park_info': None,
   'new_state': None,
   'theme_state': 'Z9999@T05@T08@T16@T17@T20@T21@T30@T32@T34@@T43@T52@T56@T57@T64@T65@T69@T71@P80@P90',
   'new_bool': 0,
   'search_text': '',
   'ins_lat': '',
   'ins_lng': '',
   'in_distance': 0,
   'out_distance': '8.65',
   'all_search_cnt': -1,
   'addr_search_cnt': -1,
   'store_search_cnt': -1,
   'rowCount': 30,
   'store_nm': '',
   'store_cd': 0,
   's_biz_code': '3912',
   'new_icon': 'N',
   'set_user': '',
   'favorites': 0,
   'map_desc': None,
   'notice': None,
   'defaultimage': '/upload/store/2020/05/[3912]_20200527074116_twz04.jpg',
   'etcimage': None,
   'in_biz_cd': None,
   'in_store_cd': None,
   'in_favorites': None,
   'in_user_id': None,
   'in_biz_cds': 0,
   'in_biz_arr': None,
   'in_biz_arrdata': None,
   'in_scodes': 0,
   'in_scode_arr': None,
   'in_scode_arrdata': None,
   'disp': None,
   'set_date': None,
   'hlytag': None,
   'hlytag_msg': None,
   'vSal': '',
   'istart': 1,
   'iend': 60,
   'open_dt': '20200528',
   'gold_card': 0,
   'ip_lat': '',
   'ip_long': '',
   'espresso': '',
   'new_store': '',
   'premiere_food': '',
   'doro_address': '서울특별시 강남구 봉은사로 619 (삼성동)',
   'cold_blew': '',
   'my_siren_order_store_yn': 'N',
   'whcroad_yn': 'WHCROAD',
   'skuNo': '',
   'skuName': '',
   'skuImgUrl': '',
   'stock_count': 0,
   'store_area_name': None,
   'store_area_code': 'A01',
   'is_open': None,
   'ev_open_yn': None,
   'option': None,
   'gift_stock_yn': None,
   'lat': '37.515',
   'lot': '127.063196',
   't20': 0,
   't04': 0,
   't03': 0,
   't01': 0,
   't12': 0,
   't09': 0,
   't06': 0,
   't10': 0,
   'p10': 0,
   'p50': 0,
   'p20': 0,
   'p60': 0,
   'p30': 0,
   'p70': 0,
   'p40': 0,
   'p80': 0,
   't22': 0,
   't21': 0,
   'p90': 0,
   'p01': 0,
   't05': 0,
   't30': 0,
   't36': 0,
   't27': 0,
   't29': 0,
   't43': 0,
   't48': 0,
   'z9999': 0,
   't64': 0,
   't66': 0,
   'p02': 0},
  {'seq': 0,
   'sido_cd': None,
   'sido_nm': None,
   'gugun_cd': None,
   'gugun_nm': None,
   'code_order': None,
   'view_yn': None,
   'store_num': None,
   'sido': None,
   'gugun': None,
   'address': None,
   'new_img_nm': None,
   'p_pro_seq': 0,
   'p_view_yn': None,
   'p_sido_cd': '',
   'p_gugun_cd': '',
   'p_store_nm': None,
   'p_theme_cd': None,
   'p_wireless_yn': None,
   'p_smoking_yn': None,
   'p_book_yn': None,
   'p_music_yn': None,
   'p_terrace_yn': None,
   'p_table_yn': None,
   'p_takeout_yn': None,
   'p_parking_yn': None,
   'p_dollar_assent': None,
   'p_card_recharge': None,
   'p_subway_yn': None,
   'stb_store_file_renew': None,
   'stb_store_theme_renew': None,
   'stb_store_time_renew': None,
   'stb_store_lsm': None,
   's_code': '1650',
   's_name': '압구정윤성빌딩',
   'tel': '1522-3232',
   'dlvry_call_cntr_phno': None,
   'fax': '02-546-3894',
   'sido_code': '01',
   'sido_name': '서울',
   'gugun_code': '0101',
   'gugun_name': '강남구',
   'addr': '서울특별시 강남구 신사동 592 윤성빌딩',
   'park_info': None,
   'new_state': None,
   'theme_state': 'Z9999@T05@T08@T16@T17@T20@T21@T30@T32@T34@@T36@@T52@T56@T57@T64@T69@P70@P80@P90',
   'new_bool': 0,
   'search_text': '',
   'ins_lat': '',
   'ins_lng': '',
   'in_distance': 0,
   'out_distance': '5.85',
   'all_search_cnt': -1,
   'addr_search_cnt': -1,
   'store_search_cnt': -1,
   'rowCount': 30,
   'store_nm': '',
   'store_cd': 0,
   's_biz_code': '3893',
   'new_icon': 'N',
   'set_user': '',
   'favorites': 0,
   'map_desc': None,
   'notice': None,
   'defaultimage': '/upload/store/2021/08/[3893]_20210828042809_9v371.jpg',
   'etcimage': None,
   'in_biz_cd': None,
   'in_store_cd': None,
   'in_favorites': None,
   'in_user_id': None,
   'in_biz_cds': 0,
   'in_biz_arr': None,
   'in_biz_arrdata': None,
   'in_scodes': 0,
   'in_scode_arr': None,
   'in_scode_arrdata': None,
   'disp': None,
   'set_date': None,
   'hlytag': None,
   'hlytag_msg': None,
   'vSal': '',
   'istart': 1,
   'iend': 60,
   'open_dt': '20200529',
   'gold_card': 0,
   'ip_lat': '',
   'ip_long': '',
   'espresso': '',
   'new_store': '',
   'premiere_food': '',
   'doro_address': '서울특별시 강남구 논현로 834 (신사동)',
   'cold_blew': '',
   'my_siren_order_store_yn': 'N',

In [10]:
st_df = json_normalize(starbucks, 'list')
st_df

,seq,sido_cd,sido_nm,gugun_cd,gugun_nm,code_order,view_yn,store_num,sido,gugun,...,t30,t36,t27,t29,t43,t48,z9999,t64,t66,p02
0,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
1,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
2,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
3,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
4,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
596,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
597,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
598,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
599,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0

In [11]:
st_df_map = st_df[['s_name','sido_code','sido_name','gugun_code','gugun_name',
'doro_address','lat','lot']]
st_df_map

,s_name,sido_code,sido_name,gugun_code,gugun_name,doro_address,lat,lot
0,역삼아레나빌딩,01,서울,0101,강남구,서울특별시 강남구 언주로 425 (역삼동),37.501087,127.043069
1,논현역사거리,01,서울,0101,강남구,서울특별시 강남구 강남대로 538 (논현동),37.510178,127.022223
2,신사역성일빌딩,01,서울,0101,강남구,서울특별시 강남구 강남대로 584 (논현동),37.5139309,127.0206057
3,국기원사거리,01,서울,0101,강남구,서울특별시 강남구 테헤란로 125 (역삼동),37.499517,127.031495
4,대치재경빌딩,01,서울,0101,강남구,서울특별시 강남구 남부순환로 2947 (대치동),37.494668,127.062583
...,...,...,...,...,...,...,...,...
595,사이버한국외대,01,서울,0122,동대문구,서울특별시 동대문구 휘경로 6 (이문동),37.5960508006499,127.060761238087
596,청량리역사,01,서울,0122,동대문구,서울특별시 동대문구 왕산로 214 (전농동) 청량리역사 Connect Place6층,37.580565324,127.048564845
597,답십리초교사거리,01,서울,0122,동대문구,서울특별시 동대문구 전농로 38 (답십리동),37.5682540295405,127.057240883237
598,장안사거리,01,서울,0122,동대문구,서울특별시 동대문구 답십리로 267 (장안동),37.5727209002351,127.070092668638
599,서울숲역,01,서울,0123,성동구,서울특별시 성동구 왕십리로 50 (성수동1가) 1층,37.541868967552624,127.04489904228212

In [12]:
st_df_map['lat'] = st_df_map['lat'].astype(float)
st_df_map['lot'] = st_df_map['lot'].astype(float)

C:\Users\Admin\AppData\Local\Temp\ipykernel_23052\3956451395.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  st_df_map['lat'] = st_df_map['lat'].astype(float)
C:\Users\Admin\AppData\Local\Temp\ipykernel_23052\3956451395.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  st_df_map['lot'] = st_df_map['lot'].astype(float)

In [ ]:
loc = [37.501087, 127.043069] 
stmap = folium.Map(location=loc, zoomstart=18)
pop = folium.Popup('역삼아레나빌딩', max_width=100)
folium.Marker(location=loc, popup=pop).add_to(stmap)
stmap

In [ ]:

stmap = folium.Map(location=[st_df_map['lat'].mean(), st_df_map['lot'].mean()], zoom_start=14)

for i, row in st_df_map.iterrows():
    folium.Marker(
        location=[row['lat'], row['lot']],  
        popup=folium.Popup('스타벅스', max_width=100)
    ).add_to(stmap)

stmap